version: "3.9"
services:
  lb-todo-api:
    build: ./api
    depends_on: 
      - mongodb
    ports:
      - "5000:3000"
  mongodb:
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
